;; (define (make-frame variables values)
;;   (cons variables values))
(define (make-frame variables values)
  (map cons variables values))
;; (define (frame-variables frame) (car frame))
(define (frame-variables frame) (map car frame))
;; (define (frame-values frame) (cdr frame))
(define (frame-values frame) (map cdr frame))
;; (define (add-binding-to-frame! var val frame)
;;   (set-car! frame (cons var (car frame)))
;;   (set-cdr! frame (cons val (cdr frame))))
(define (add-binding-to-frame! var val frame)
  (set-cdr! frame (cons (cons var val) (cdr frame))))
