(define (make-account balance password)
  (let ((failed-access 0))
    (define (withdraw amount)
      (if (>= balance amount)
          (begin (set! balance (- balance amount))
                 balance)
          "Insufficient funds"))
    (define (deposit amount)
      (set! balance (+ balance amount))
      balance)
    (define (dispatch key m)
      (cond ((not (eq? key password))
             (begin (set! failed-access (+ failed-access 1))
                    (if (>= failed-access 7)
                        (call-the-cops)
                        (error "Incorrect password"))))
            ((eq? m 'withdraw) withdraw)
            ((eq? m 'deposit) deposit)
            (else (error "Unknown request -- MAKE-ACCOUNT"
                         m))))
    (define (call-the-cops)
      (display "Call The Cops!!")
      (newline))
    dispatch))

(define acc (make-account 100 'secret-password))
((acc 'secret-password 'withdraw) 40)
((acc 'some-other-password 'deposit) 50)
