(define draw-frame-outline
  (let ((v0 (make-vect 0.0 0.0))
        (v1 (make-vect 1.0 0.0))
        (v2 (make-vect 1.0 1.0))
        (v3 (make-vect 0.0 1.0)))
    (segments->painter (list (make-segment v0 v1)
                             (make-segment v1 v2)
                             (make-segment v2 v3)
                             (make-segment v3 v0)))))

(define draw-frame-x
  (let ((v0 (make-vect 0.0 0.0))
        (v1 (make-vect 1.0 1.0))
        (v2 (make-vect 0.0 1.0))
        (v3 (make-vect 1.0 0.0)))
    (segments->painter (list (make-segment v0 v1)
                             (make-segment v2 v3)))))

(define draw-frame-rhombus
  (let ((v0 (make-vect 0.0 0.5))
        (v1 (make-vect 0.5 0.0))
        (v2 (make-vect 1.0 0.5))
        (v3 (make-vect 0.5 1.0)))
    (segments->painter (list (make-segment v0 v1)
                             (make-segment v1 v2)
                             (make-segment v2 v3)
                             (make-segment v3 v0)))))

(define wave
  (segments->painter (list (make-segment (make-vect 0 0.6) (make-vect 0.2 0.4))
                           (make-segment (make-vect 0.2 0.4) (make-vect 0.3 0.55))
                           (make-segment (make-vect 0.3 0.55) (make-vect 0.35 0.45))
                           (make-segment (make-vect 0.35 0.45) (make-vect 0.25 0))
                           (make-segment (make-vect 0.4 0) (make-vect 0.5 0.3))
                           (make-segment (make-vect 0.5 0.3) (make-vect 0.6 0))
                           (make-segment (make-vect 0.75 0) (make-vect 0.6 0.45))
                           (make-segment (make-vect 0.6 0.45) (make-vect 0.99 0.15))
                           (make-segment (make-vect 0 0.8) (make-vect 0.2 0.55))
                           (make-segment (make-vect 0.2 0.55) (make-vect 0.3 0.6))
                           (make-segment (make-vect 0.3 0.6) (make-vect 0.4 0.6))
                           (make-segment (make-vect 0.4 0.6) (make-vect 0.35 0.8))
                           (make-segment (make-vect 0.35 0.8) (make-vect 0.4 0.99))
                           (make-segment (make-vect 0.6 0.99) (make-vect 0.65 0.8))
                           (make-segment (make-vect 0.65 0.8) (make-vect 0.6 0.6))
                           (make-segment (make-vect 0.6 0.6) (make-vect 0.8 0.6))
                           (make-segment (make-vect 0.8 0.6) (make-vect 0.99 0.35)))))
